<?php

/**
 * 数据跟踪
 */
class TrackController extends TCApiControllerBase {

  private $json = null;

  protected function postOnlyActions(){
    return array('index');
  }

  public function init() {
    parent::init(); // TODO: Change the autogenerated stub
    $this->json = $this->getJson();
  }

  private function getJson() {
    $json = null;
    $data = file_get_contents("php://input");
    if(!empty($data)){
      $json = @json_decode($data);
    }
    return $json;
  }


  /**
   * 客户端跟踪数据上传
   * 上传说明请参考【{@link documentForTrack}】
   * @json:{
   *   "status": "success",          // 接口返回状态，sucess表示成功，error表示失敗
   *   "message": "error message",   // 失败原因
   * }
   */
  public function indexAction(){
    if(!$this->json) return $this->writeErrorJsonResponse("数据格式错误");
    $log = date("Y-m-d H:i:s") . "\t" . $_SERVER['REMOTE_ADDR'] . "\t" . json_encode($this->json) . "\n";
    $file_name = APPLICATION_DIRECTORY . "/runtime/track/index/" . date("Y-m-d") . ".log";
    if(!@file_put_contents($file_name, $log, FILE_APPEND)) {
      @mkdir(dirname($file_name), 0777, true);
      @file_put_contents($file_name, $log, FILE_APPEND);
    }
    return $this->writeSuccessJsonResponse();
  }

}